config/routes.rb
Rails.application.routes.draw do

  get 'tasks', to: 'tasks#index'

  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'

  get 'tasks/:id', to: 'tasks#show', as: :task

  get 'tasks/:id/edit', to: 'tasks#edit'
  patch 'tasks/:id', to: 'tasks#update'

  delete 'tasks/:id', to: 'tasks#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:description, :complete)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.text_field :description, placeholder: "Task"%>
  <%= f.label :complete %>
  <%= f.check_box :complete %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>FORMS_Edit</h1>
<%= render 'form' %>

app/views/tasks/index.html.erb
<div class="container head">
  <h1>Task List</h1>
  <%= link_to "Create", tasks_new_path(@task) %>
</div>

<div class="container">
  <ul>
    <% @tasks.each do |task| %>
      <li>
        <div> <%= "<strong>Task:</strong> #{task.description}".html_safe %></div>
        <div class="details">
          <%= "<strong>Complete?</strong> #{task.complete}".html_safe %>
          <%= link_to "Edit", task_path(task) %>
          <%= link_to "Delete", task_path(task.id), method: :delete, data: { confirm: "Are you sure?" } %>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/tasks/new.html.erb
<h1>FORMS_NEW</h1>
<%= render 'form' %>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<%= @task %>